version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=yourdbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
      - ./customer_data.xlsx:/app/customer_data.xlsx  
      - ./loan_data.xlsx:/app/loan_data.xlsx 
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env


volumes:
  postgres_data:
