# Generated by Django 5.2.4 on 2025-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approved_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
